spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(kpubFcC8tHhp/kfL64nfpcvN8YAzpFYMZPz3LiTNMhBK8Nvf8LaHQTOeyhCesgq7)
    username: ENC(HuGj6bz1mbfrNC3qh6Tb7g==)
    password: ENC(vwm1CjAKsdqDy2GbZy6VZg==)

  jasypt:
    encryptor:
      bean: jasyptStringEncryptor
      password: ${ENCRYPT_KEY}

  data:
    redis:
      host: ENC(9FKkZEjzT6gsP+g6Xkc1rTvvjeC4i5KY)
      port: 6379
      password: ENC(FOMb9bdSbhti8LOnMC5NB/AfsR0gKbV5)

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database: mysql
    defer-datasource-initialization: true

  jwt:
    secret: ENC(bJtmrRD6R/UOPjiY/1N0LtCT8USf2CVh6UC9ESc6vh5BE8gLZ/YD9eTnD9yDzwwGtDUw+gAjwDvoQqrIfFfrPA4gwleTWLt9aXXuLgKCEEoHBLaR0PJwrj06aSeF1rDWGL1VAXG1gl7H8OkjsranN9bu/e8IykbOR9AX3nT9gkWYz747TTYbqQItL8nvA/e9)
    access-token-expiration-time: ENC(ZdL6uy0mw5FiJGtTkDul2A==)
    refresh-token-expiration-time: ENC(2KzuRJlWzm2+F5F5i/MekMP+wlski1Ty)

logging:
  level:
    root: INFO


