version: "3"
services:
  db:
    image: mysql:8.0.32
    container_name: oauth-mysql-server
    ports:
      - "3309:3306"
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./data/:/var/lib/mysql
  redis:
    image: redis:latest
    container_name: oauth-redis-server
    command: redis-server --requirepass ${REDIS_PASSWORD} --port 6380
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - "6380:6380"
    env_file:
      - .env
    volumes:
      - ./redis/data:/data
      - ./redis/conf/redis.conf:/usr/local/conf/redis.conf